# Generated by Django 4.2.3 on 2023-07-09 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cryptoexchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cryptoexchange.coin",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cryptoexchange.customer",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="coin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cryptoexchange.coin",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cryptoexchange.customer",
            ),
        ),
    ]
