# Generated by Django 4.2.3 on 2023-07-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cryptoexchange", "0002_order_coin_order_customer_stock_coin_stock_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stockvalue",
            field=models.FloatField(null=True),
        ),
    ]
